services:
  - type: web
    name: whatsapp-api-supabase
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    healthCheck:
      path: /api/status
    envVars:
      - key: SUPABASE_URL # سيتم إدخال القيمة من لوحة تحكم Render
        sync: false
      - key: SUPABASE_KEY # سيتم إدخال القيمة من لوحة تحكم Render
        sync: false
      - key: SESSION_ID # معرف فريد للجلسة، مثلاً 'my-session-1'
        value: "my-whatsapp-session"
